// <auto-generated />
using System;
using GPSMiniMap.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPSMiniMap.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("GPSMiniMap.Database.GeocodeRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("RealName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("GeocodeCache");
                });

            modelBuilder.Entity("GPSMiniMap.Database.LocationRecord", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<float>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<float>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<float>("AltitudeAccuracy")
                        .HasColumnType("REAL");

                    b.Property<float>("Heading")
                        .HasColumnType("REAL");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Speed")
                        .HasColumnType("REAL");

                    b.HasKey("Time");

                    b.ToTable("LocationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
